//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodHamburguer.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoodHamburguer.Domain.Resources.ResourceExceptionMessages", typeof(ResourceExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot contain more than one sandwich, fries or soda..
        /// </summary>
        public static string CANNOT_CONTAIN_MORE_THAN_ONE_SANDWICH_FRIES_OR_SODA {
            get {
                return ResourceManager.GetString("CANNOT_CONTAIN_MORE_THAN_ONE_SANDWICH_FRIES_OR_SODA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid drink..
        /// </summary>
        public static string INVALID_DRINK {
            get {
                return ResourceManager.GetString("INVALID_DRINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid fries..
        /// </summary>
        public static string INVALID_FRIES {
            get {
                return ResourceManager.GetString("INVALID_FRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sandwich..
        /// </summary>
        public static string INVALID_SANDWICH {
            get {
                return ResourceManager.GetString("INVALID_SANDWICH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select at least one quantity of the item..
        /// </summary>
        public static string MUST_SELECT_AT_LEAST_ONE_QUANTITY {
            get {
                return ResourceManager.GetString("MUST_SELECT_AT_LEAST_ONE_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No orders were found..
        /// </summary>
        public static string NO_ORDERS_WERE_FOUND {
            get {
                return ResourceManager.GetString("NO_ORDERS_WERE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order not found..
        /// </summary>
        public static string ORDER_NOT_FOUND {
            get {
                return ResourceManager.GetString("ORDER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose at least one item from the menu..
        /// </summary>
        public static string PLEASE_CHOOSE_AT_LEAST_ONE_ITEM_FROM_THE_MENU {
            get {
                return ResourceManager.GetString("PLEASE_CHOOSE_AT_LEAST_ONE_ITEM_FROM_THE_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create order..
        /// </summary>
        public static string UNABLE_TO_CREATE_ORDER {
            get {
                return ResourceManager.GetString("UNABLE_TO_CREATE_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update order..
        /// </summary>
        public static string UNABLE_TO_UPDATE_ORDER {
            get {
                return ResourceManager.GetString("UNABLE_TO_UPDATE_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
    }
}
